services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - default

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - default

networks:
  default: